typography_spectrum: 0.48199758590401914
color:
  brandStrength: 0.7132495255466772
  lightness: 0.689285168450252
  saturation: 0.5494571447133613
  rhythmicContrast: 0.8536991983029696
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#808080'
    - '#DBDBDB'
    - '#B3B3B3'
github: true
layout_spectrum: 0.5835345619844069
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5c387489-43e2-4999-b07a-10bfb7af5392.png
name: Zachari.co
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8e47b456-5244-43f9-9280-a4fc606bce89.png
title: Welcome to my portfolio
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FNZlfxWMr7nc%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DNZlfxWMr7nc&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FNZlfxWMr7nc%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: BaLu - Relaxing Nature
          url: 'https://www.youtube.com/channel/UCUTOwFZ5grVnUMvvleA_JMg'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://www.youtube.com/favicon.ico'
        domain: www.youtube.com
      keywords: []
      description: >-
        Relaxing music and Beautiful Aurora Borealis. Helps Relax & Fall Asleep
        FAST! 2 hour long. Music for relaxation, sleep, meditation, yoga, study.
        sit back, relax and enjoy :) ▼ See More! ▼ Check our new Printable
        Antistress Coloring eBook for kids and adults. Drawings include fishes,
        coral reefs, turtles and more!
      '@type': VideoObject
      app_links: []
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=NZlfxWMr7nc'
      title: >-
        Relax Music & Stunning Aurora Borealis - Northern Polar Lights - 2 Hours
        - HD 1080P
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: DIGItal ARTist
purpose:
  - type: contact
    url: 'mailto:hello@zachari.co'
    label: mail me
  - type: contact
    url: 'tel:0455376373'
    label: phone me
